### PR TITLE
Avoid to import binary and use the SNAPSHOT dependencies

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
as @jsarenik suggested on IRC (#c-lightning) the plugin use a developing version of the last jar and avoid to bring in the devlib the jar

### CODE REVIEW

**Comment by jsarenik** [comment]
@vincenzopalazzo amazing! Thank you! Didn't have to move a finger :)

**Comment by vincenzopalazzo** [comment]
@jsarenik :-D, i will suppose that you don't have a problem with the plugin, any crash to report? or we can move to mainet?

**Comment by jsarenik** [comment]
@vincenzopalazzo no crash, though I am not running 24/7, it was humming marrily for hours at least (unlike `esplora_clnd_plugin` plugin error reported in https://github.com/lightningamp/esplora_clnd_plugin/issues/47).

**Comment by vincenzopalazzo** [comment]
We will catch the error in the `esplora_clnd_plugin` too, this plugin can help to understand how it important have an error recovery. 

Another thing, if you have a log file can you run this command `cat path/logFile.log | grep retry` for me and report the result?

**Comment by jsarenik** [comment]
@vincenzopalazzo do you mean log file of a `lightningd` running with `btcli4j` plugin?

**Comment by vincenzopalazzo** [comment]
@jsarenik yes exactly

**Comment by vincenzopalazzo** [comment]
@jsarenik no error at all, good news

By default now the plugin retries the request 4 time with an increase waiting time if you want know how many time the plugin was able to recover an error, you can use this command

**Pull request merged**
